export const storeProducts = [
  {
    id: 1,
    title: "",
    img: "img/plant2.jpeg",
    price: "contact judejim5609@gmail.com",
    company: "",
    info: "",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "",
    img: "img/plant-3.jpeg",
    price: "contact judejim5609@gmail.com",
    company: "SAMSUNG",
    info: ".",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "",
    img: "img/plant-4.jpeg",
    price: "contact judejim5609@gmail.com",
    company: "htc",
    info: ".",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "",
    img: "img/plant-5.jpeg",
    price: "contact judejim5609@gmail.com",
    company: "htc",
    info: ".",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "",
    img: "img/palnt6.jpeg",
    price: "contact judejim5609@gmail.com",
    company: "htc",
    info: ".",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "",
    img: "img/plant-7.jpeg",
    price: "contact judejim5609@gmail.com",
    company: "apple",
    info: ".",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "",
    img: "img/plant-8.jpeg",
    price: "contact judejim5609@gmail.com",
    company: "apple",
    info: ".",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "",
    img: "img/plant10.jpeg",
    price: "contact judejim5609@gmail.com",
    company: "apple",
    info: ".",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "",
  img: "img/plant10.jpeg",
  price: "contact judejim5609@gmail.com",
  company: "",
  info: ".",
  inCart: false,
  count: 0,
  total: 0,
};
